version: '3'
services:
  db:
    image: postgres
    env_file:
      - path: ./server/.env.development
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - '${DATABASE_PORT}:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  redis:
    container_name: redis
    image: redis
    env_file:
      - path: ./server/.env.development
    ports:
        - ${REDIS_PORT}:6379

